"use client";
import React, { useState, useEffect, useMemo } from "react";
import { X, ArrowLeft, MessageCircle, ShoppingCart, Check, Minus, Plus, Truck, ShieldCheck, Info, Maximize2 } from "lucide-react";
import { db } from "@/lib/firebase";
import { collection, doc, onSnapshot } from "firebase/firestore";
import { useCartStore } from "@/store/useCartStore";
interface ProductDetailModalProps { product: any; onClose: () => void; }
const ProductDetailModal = ({ product, onClose }: ProductDetailModalProps) => {
  const [whatsappNumber, setWhatsappNumber] = useState("86153695");
  const addItem = useCartStore((state) => state.addItem);
  const [attributeDefinitions, setAttributeDefinitions] = useState<any[]>([]);
  const [selectedAttributes, setSelectedAttributes] = useState<Record<string, string>>({});
  const [selectedColor, setSelectedColor] = useState<any>(null), [quantity, setQuantity] = useState(1), [addedToQuote, setAddedToQuote] = useState(false), [activeImageIndex, setActiveImageIndex] = useState(0), [isImageZoomed, setIsImageZoomed] = useState(false);
  useEffect(() => {
    const unsubConfig = onSnapshot(doc(db, "configuracion", "general"), snap => { if (snap.exists() && snap.data().whatsapp) setWhatsappNumber(snap.data().whatsapp.trim()); });
    const unsubAttrs = onSnapshot(collection(db, "atributos_globales"), snap => setAttributeDefinitions(snap.docs.map(d => ({ id: d.id, ...d.data() }))));
    return () => { unsubConfig(); unsubAttrs(); };
  }, []);
  const imagesList = useMemo(() => product.imagenes?.length > 0 ? product.imagenes : (product.imagenUrl ? [product.imagenUrl] : []), [product]);
  const productAttributes = useMemo(() => {
    if (Array.isArray(product.atributos)) return product.atributos.map((a: any) => ({ ...a, definition: attributeDefinitions.find(d => d.id === a.atributoId) })).filter((a: any) => a.atributoId);
    return Object.entries(product.atributos || {}).map(([key, valores]: any) => ({ atributoId: key, valores: Array.isArray(valores) ? valores : [valores], definition: attributeDefinitions.find(d => d.id === key || d.nombreAtributo === key) }));
  }, [product, attributeDefinitions]);
  useEffect(() => {
    setActiveImageIndex(0); setIsImageZoomed(false);
    const defaults: Record<string, string> = {}; productAttributes.forEach((a: any) => { if (a.valores?.length) defaults[a.atributoId] = a.valores[0]; }); setSelectedAttributes(defaults);
    setSelectedColor(product.colores?.length ? product.colores[0] : null);
  }, [product, productAttributes]);
  const unitPrice = useMemo(() => { if (!product.escalasPrecios?.length) return 0; const escala = product.escalasPrecios.find((e: any) => quantity >= e.min && quantity <= e.max); return escala ? escala.price : product.escalasPrecios[product.escalasPrecios.length - 1].price; }, [quantity, product.escalasPrecios]);
  const totalPrice = unitPrice * quantity;
  const handleDirectOrder = () => { const attrString = productAttributes.map((a: any) => `• *${a.definition?.nombreAtributo || "Atributo"}:* ${selectedAttributes[a.atributoId] || "N/A"}`).join("\n"); const message = `¡Hola SubliMod! Me interesa este producto:\n\n- *Producto:* ${product.nombre}\n- *Cantidad:* ${quantity} unidades\n${attrString}\n- *Variante/Color:* ${selectedColor?.name || "N/A"}\n\n- *Precio Unitario:* C$ ${unitPrice}\n- *Total Estimado:* C$ ${totalPrice}\n\n_Enlace del producto:_ ${window.location.origin}/producto/${product.id}\nQuedo a la espera de su respuesta para coordinar el diseño.`; window.open(`https://wa.me/505${whatsappNumber}?text=${encodeURIComponent(message)}`, "_blank"); };
  const handleAddToQuote = () => { addItem({ id: `${product.id}-${Date.now()}`, productId: product.id, nombre: product.nombre, imagen: product.imagenUrl, atributos: selectedAttributes, color: selectedColor, cantidad: quantity, precioUnitario: unitPrice, total: totalPrice }); setAddedToQuote(true); setTimeout(() => setAddedToQuote(false), 2000); };
  return <div className="fixed inset-0 bg-secondary/35 backdrop-blur-md z-[100] flex items-center justify-center p-0 lg:p-6 overflow-hidden"><div className="bg-[#F8FAFA] w-full max-w-5xl h-dvh lg:h-auto lg:max-h-[90vh] lg:my-auto rounded-none lg:rounded-[2.5rem] border border-white shadow-2xl overflow-hidden relative animate-in zoom-in duration-300 flex flex-col">
    <div className="lg:hidden shrink-0 flex items-center justify-between gap-3 px-4 py-3 bg-[#F8FAFA] border-b border-primary/10"><button type="button" onClick={onClose} className="inline-flex items-center gap-2 min-h-11 px-3 rounded-xl text-secondary"><ArrowLeft size={20}/><span className="text-xs font-black uppercase tracking-widest">Volver</span></button><span className="text-[9px] font-black text-gray-400 uppercase tracking-[0.2em]">Detalle del producto</span><button type="button" onClick={onClose} className="inline-flex items-center justify-center min-h-11 min-w-11 rounded-xl bg-white"><X size={20}/></button></div>
    <button onClick={onClose} className="hidden lg:block absolute top-5 right-5 z-50 p-3 bg-white/80 rounded-full text-secondary shadow-md" aria-label="Cerrar detalle"><X size={22}/></button>
    <div className="grid grid-cols-1 lg:grid-cols-2 flex-1 min-h-0 overflow-y-auto lg:overflow-hidden"><div className="bg-[#EEF4F3] p-6 sm:p-8 lg:p-12 flex flex-col items-center justify-center space-y-6 border-b lg:border-b-0 lg:border-r border-primary/10">{imagesList.length > 0 && <button type="button" onClick={() => setIsImageZoomed(true)} className="relative w-full aspect-square max-w-[400px] cursor-zoom-in group rounded-3xl overflow-hidden bg-white/60 border border-white"><img src={imagesList[activeImageIndex]} alt={product.nombre} className="w-full h-full object-contain p-4"/><span className="absolute bottom-4 right-4 bg-white/90 text-secondary px-3 py-2 rounded-xl shadow-md text-[9px] font-black uppercase opacity-0 group-hover:opacity-100 flex items-center gap-2"><Maximize2 size={13}/> Ampliar</span></button>}{imagesList.length > 1 && <div className="flex gap-3 overflow-x-auto w-full max-w-[400px] justify-center">{imagesList.map((img: string, idx: number) => <button key={idx} onClick={() => setActiveImageIndex(idx)} className={`shrink-0 w-16 h-16 rounded-xl overflow-hidden border-2 ${activeImageIndex === idx ? "border-primary scale-110" : "border-white opacity-70"}`}><img src={img} alt="" className="w-full h-full object-cover"/></button>)}</div>}<div className="bg-white px-5 py-2.5 rounded-2xl border border-primary/10 flex items-center gap-2"><ShieldCheck size={18} className="text-primary"/><span className="text-[10px] font-bold text-secondary uppercase">Calidad SubliMod</span></div></div>
    <div className="p-6 sm:p-8 lg:p-12 space-y-10 lg:max-h-[90vh] lg:overflow-y-auto bg-[#F8FAFA]"><div><div className="flex items-center gap-2 mb-3"><span className="bg-primary/10 text-primary text-[10px] font-black px-3 py-1 rounded-full uppercase border border-primary/20">{product.categoria}</span></div><h2 className="text-3xl lg:text-4xl font-black text-secondary uppercase tracking-tighter">{product.nombre}</h2>{product.descripcion && <p className="text-gray-600 text-sm mt-4 leading-relaxed italic">{product.descripcion}</p>}</div>
      <div className="space-y-8">{productAttributes.map((attr: any) => <div key={attr.atributoId} className="space-y-4"><label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em]">{attr.definition?.nombreAtributo || "Atributo"}</label><div className="flex flex-wrap gap-2">{(attr.valores || []).map((opt: string) => { const selected = selectedAttributes[attr.atributoId] === opt; return <button key={opt} onClick={() => setSelectedAttributes(prev => ({ ...prev, [attr.atributoId]: opt }))} className={`px-5 py-2.5 rounded-xl text-xs font-bold border transition-all flex items-center gap-2 ${selected ? "bg-primary border-primary text-white shadow-lg" : "bg-white border-gray-200 text-gray-600"}`}>{selected && <Check size={14}/>} {opt}</button>; })}</div></div>)}{product.colores?.length > 0 && <div className="space-y-4"><label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.2em]">Variante de Diseño</label><div className="flex flex-wrap gap-3">{product.colores.map((color: any) => { const selected = selectedColor?.name === color.name; return <button key={color.name} onClick={() => setSelectedColor(color)} className={`flex items-center gap-3 p-1.5 pr-4 rounded-2xl border ${selected ? "border-primary bg-primary/10" : "border-gray-200 bg-white"}`}><div className="w-8 h-8 rounded-xl border" style={{backgroundColor: color.hex}}/><span className="text-[10px] font-bold uppercase">{color.name}</span></button>; })}</div></div>}</div>
      <div className="bg-white p-6 sm:p-8 rounded-[2rem] border border-primary/10 space-y-8"><div className="flex flex-col md:flex-row justify-between items-center gap-6"><div className="space-y-3 w-full md:w-auto"><label className="text-[10px] font-black text-gray-500 uppercase block">Cantidad</label><div className="flex items-center justify-between bg-[#F8FAFA] border border-gray-200 rounded-2xl p-1"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} className="p-3"><Minus size={20}/></button><span className="text-xl font-black text-primary w-12 text-center">{quantity}</span><button onClick={() => setQuantity(quantity + 1)} className="p-3"><Plus size={20}/></button></div></div><div className="text-center md:text-right"><label className="text-[10px] font-black text-gray-500 uppercase block">Total Estimado</label><div className="text-4xl font-black text-accent">C$ {totalPrice}</div><span className="text-[10px] font-bold text-gray-500 uppercase">C$ {unitPrice} por unidad</span></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><button onClick={handleDirectOrder} className="bg-primary text-white py-5 rounded-2xl font-black text-sm uppercase tracking-widest flex items-center justify-center gap-3"><MessageCircle size={20}/> Personalizar y Pedir</button><button onClick={handleAddToQuote} className={`py-5 rounded-2xl font-black text-sm uppercase flex items-center justify-center gap-3 border-2 ${addedToQuote ? "bg-green-500/10 border-green-500 text-green-500" : "bg-white border-gray-200 text-secondary"}`}>{addedToQuote ? <><Check size={20}/> ¡Añadido!</> : <><ShoppingCart size={20}/> Añadir a Cotización</>}</button></div></div>
      <div className="flex flex-col md:flex-row gap-6 border-t border-primary/10 pt-8"><div className="flex items-center gap-3 text-gray-600"><Truck size={18} className="text-primary"/><span className="text-[10px] font-bold uppercase">Envíos Cargo Trans / Interlocal</span></div><div className="flex items-center gap-3 text-gray-600"><Info size={18} className="text-primary"/><span className="text-[10px] font-bold uppercase">Jinotega, Nicaragua</span></div></div>
    </div></div>
    {isImageZoomed && imagesList.length > 0 && <div className="fixed inset-0 z-[300] bg-secondary/80 backdrop-blur-lg flex items-center justify-center p-4" onClick={() => setIsImageZoomed(false)}><button onClick={() => setIsImageZoomed(false)} className="absolute top-5 right-5 w-12 h-12 rounded-full bg-white text-secondary shadow-xl flex items-center justify-center"><X size={24}/></button><img src={imagesList[activeImageIndex]} alt={product.nombre} className="max-w-[95vw] max-h-[90vh] object-contain rounded-2xl" onClick={e => e.stopPropagation()}/></div>}
  </div>;
};
export default ProductDetailModal;
