import type { TechnologyCategory } from "./types";

export const predefinedTechnologyCategories: Omit<TechnologyCategory, "id">[] = [
  {
    name: "Laptops",
    slug: "laptops",
    description: "Computadoras portátiles y notebooks.",
    visible: true,
    order: 10,
    specificationFields: [
      { id: "brand", label: "Marca", type: "text", required: true, order: 1 },
      { id: "cpu", label: "Modelo de CPU", type: "text", required: true, order: 2 },
      { id: "modelName", label: "Nombre del modelo", type: "text", order: 3 },
      { id: "screenSize", label: "Tamaño de pantalla", type: "text", order: 4 },
      { id: "color", label: "Color", type: "text", order: 5 },
      { id: "storage", label: "Capacidad del disco duro", type: "text", required: true, order: 6 },
      { id: "ram", label: "Tamaño de la memoria RAM instalada", type: "text", required: true, order: 7 },
      { id: "os", label: "Sistema operativo", type: "text", order: 8 },
      { id: "specialFeature", label: "Característica especial", type: "text", order: 9 },
      { id: "graphics", label: "Descripción de la tarjeta gráfica", type: "text", order: 10 },
      { id: "storageType", label: "Tecnología del disco duro", type: "text", order: 11 },
      { id: "weight", label: "Unidad de peso", type: "text", order: 12 },
      { id: "processorManufacturer", label: "Fabricante del procesador", type: "text", order: 13 },
      { id: "specificUses", label: "Usos específicos del producto", type: "text", order: 14 },
      { id: "formFactor", label: "Factor de forma", type: "text", order: 15 },
      { id: "driveInterface", label: "Interfaz del disco duro", type: "text", order: 16 },
      { id: "compatibleDevices", label: "Dispositivos compatibles", type: "text", order: 17 },
      { id: "warrantyType", label: "Tipo de garantía", type: "text", order: 18 },
      { id: "videoOutput", label: "Salida de vídeo", type: "text", order: 19 },
      { id: "osFamily", label: "Familia del sistema operativo", type: "text", order: 20 },
    ],
  },
  {
    name: "Computadoras de escritorio",
    slug: "computadoras-escritorio",
    description: "Computadoras de escritorio y equipos de oficina o trabajo.",
    visible: true,
    order: 20,
    specificationFields: [
      { id: "brand", label: "Marca", type: "text", required: true, order: 1 },
      { id: "modelNumber", label: "Número de modelo", type: "text", order: 2 },
      { id: "modelName", label: "Nombre del modelo", type: "text", order: 3 },
      { id: "cpu", label: "Modelo de CPU", type: "text", order: 4 },
      { id: "ram", label: "Memoria RAM", type: "text", order: 5 },
      { id: "storage", label: "Capacidad del disco duro", type: "text", order: 6 },
      { id: "storageType", label: "Tecnología del disco duro", type: "text", order: 7 },
      { id: "graphics", label: "Tarjeta gráfica", type: "text", order: 8 },
      { id: "os", label: "Sistema operativo", type: "text", order: 9 },
      { id: "formFactor", label: "Factor de forma", type: "text", order: 10 },
      { id: "included", label: "Contenido de la caja", type: "text", order: 11 },
      { id: "videoOutput", label: "Salida de vídeo", type: "text", order: 12 },
      { id: "warranty", label: "Descripción de la garantía", type: "text", order: 13 },
      { id: "compatibleDevices", label: "Dispositivos compatibles", type: "text", order: 14 },
    ],
  },
  {
    name: "Monitores",
    slug: "monitores",
    description: "Monitores y pantallas para computadora.",
    visible: true,
    order: 30,
    specificationFields: [
      { id: "brand", label: "Marca", type: "text", required: true, order: 1 },
      { id: "modelNumber", label: "Número de modelo", type: "text", order: 2 },
      { id: "modelName", label: "Nombre del modelo", type: "text", order: 3 },
      { id: "screenSize", label: "Tamaño de pantalla", type: "text", required: true, order: 4 },
      { id: "resolution", label: "Resolución", type: "text", order: 5 },
      { id: "aspectRatio", label: "Relación de aspecto", type: "text", order: 6 },
      { id: "panelType", label: "Tipo de panel", type: "text", order: 7 },
      { id: "refreshRate", label: "Frecuencia de actualización", type: "text", order: 8 },
      { id: "responseTime", label: "Tiempo de respuesta", type: "text", order: 9 },
      { id: "screenSurface", label: "Descripción de la superficie de pantalla", type: "text", order: 10 },
      { id: "viewingAngle", label: "Ángulo de visión", type: "text", order: 11 },
      { id: "features", label: "Características del producto", type: "text", order: 12 },
      { id: "videoInputs", label: "Entradas / salidas de vídeo", type: "text", order: 13 },
      { id: "warranty", label: "Descripción de la garantía", type: "text", order: 14 },
      { id: "included", label: "Contenido de la caja", type: "text", order: 15 },
    ],
  },
];
